### ISSUE TITLE
Code Formating

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#10]
Als Entwickler möchte ich sicherstellen, dass wir eine Einheitliche Codebase haben. Dies erleichtert das finden und beheben von allfälligen Bugs enorm.

### Anforderungen
- Der Code wird nach einem Vordefinierten Format einheitlich geformatted.
- Das Formatting wird automatisch bei einem Git commit mit einem precommit hook ausgeführt.
- Auf der Pipeline läuft der Formatter ebenfalls. 
- Falls möglich ein Config file für das Formatieren des Codes einchecken, welches dann verwendet wird um das Format sicherzustellen.

### Akzeptanzkriterien
- [x] Nur code der dem Format entspricht kann gemerged werden.
- [x] Für alle entwickler existieren die gleichen Formatregeln

**Comment by RandomTannenbaum** [comment]
- [ ] Formatter plugin einbinden
- [ ] Pre-commit hook erstellen und setup script dafür schreiben
- [ ] Formatting in neuem github workflow verifizieren
- [ ] Dokumentation updaten
