### ISSUE TITLE
Installation and Configuration Guide

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#102]
Als Kunde möchte ich anhand eines **Installation and Configuration Guide** die App lokal installieren und betreiben können.

TODO: weitere Details beschreiben inkl. Anforderungen, Akzeptanzkriterien, Aufwandschätzung

**Comment by MasterEvarior** [comment]
Die Installation und Konfiguration wird durch /sys durchgeführt. Der Installation-Guide wird also nicht mehr benötigt bzw. von uns gemacht.
