### ISSUE TITLE
Keine Fehlermeldungen im UI

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#104]
Als Entwickler möchte ich keine Fehlermeldungen in der Console des Web Browsers sehen (im Normalfall). Vorhandene Fehlermeldungen müssen analysiert und gelöst oder deren Ursache dokumentiert werden.

### Anforderungen
- Alle ungwollte Fehlermeldungen wurden aus der Konsole enfernt
- Im falle das die Fehlermeldung nicht entfernt werden kann wurde dies beim Ursprung so dokumentiert

### Akzeptanzkriterien
- [x] Alle Anforderungen wurden erfüllt
- [x] Das feature wurde smoke getestet

**Comment by ManuelMoeri** [comment]
### Stand 24.09.2024
Ich bin heute auf einige Fehler gestossen, ein paar welche ich noch nicht lösen konnte. Ein grossteil der Fehler wurde durch das JS handling des Input-Buttons ausgelöst. Da alle js files jedoch mit #106 entfernt geworden sind, tretten diese Fehler nicht mehr auf.

Im moment bin ich noch am Fehler dran das im 'exam-number-input.html' file dies hier
```
<input type="text" name="examNumber" oninput="this.value = this.value.replace(/\D+/g, '')"
               placeholder="20202" th:value="*{examNumber}" th:maxlength="5" required>
```
von der Content-Security-Policy als JS erkannt wird und JS muss gewhitelisted werden.

Der zweite Fehler denn ich noch habe ist ein problem das nur in Chrome auftritt. Dort erscheint im moment noch ein Error mit den Permission-Policy header.
