### ISSUE TITLE
Frontendfiles formatter

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/unilu-pruefungsabfrage#114]
Als Entwickler möchte ich das mein Frontend code automatisch konsistent formatiert wird.

### Anforderungen

- Frontend formatter ohne npm (via mvn)
- Der Formatter wird automatisiert auf der pipeline ausgeführt

### Akzeptanzkriterien

- [ ] Die aufgeführten Anforderungen sind alle erfüllt.
- [ ] Die Tests sind entsprechend angepasst.

**Comment by RandomTannenbaum** [comment]
**Stand 02.10.2024**
Ich habe das ticket gerebased und die conversations resolved.
