### ISSUE TITLE
Service erstellen für Prüfung aus FS auslesen

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#12]
Um sicherzustellen, dass der Eingeloggte Student seine und nur seine Prüfungen einsehen kann, brauchen wir einen Service. Dieser Service bleibt sehr klein, da die Applikation nicht viele Funktionen hat. 

### Anforderungen
- Der Service bindet den Validierungsservice ein
- Der Service findet anhand einer 5 stelligen Prüfungslaufnummer und der 8 Stelligen Matrikel nummer im Format : `24000_19103106` alle Prüfungen auf dem Server der dieser Nummer zugeordnet werden kann. 
- Als Ergebnis der Suche soll eine Liste mit den Prüfungen, welche den Ordnernamen haben erscheinen.

### Akzeptanzkriterien
- [x] Der Service handelt die komplette Business Logik
- [x] Der Service ist sauber getestet.
- [x] Die Daten für Prüfungslaufnummer und Matrikelnummer werden zum start HardCodiert
- [ ] Die oben gelisteten Anforderungen sind vollumfänglich erfüllt.

**Comment by ManuelMoeri** [comment]
### Stand 29.08.2024
Die Grundfunktionalität des Tickets steht. Hier sind noch ein paar dinge die zu beachten / zu erledigen sind:
- [ ] Exception handling / logging. Es kommt 2 mal vor das eine leere Liste zurückgegeben wird. Einmal wird eine message geloggt und einmal nicht. Schauen ob die implementation des loggers okay ist & ob logging beim anderen Falle auch sinnvoll wäre. Logging bei der Exception würde vielleicht auch sinn machen.
- [ ] Es hat stand jetzt einen Test der plötzlich wie aus dem nichts failed. Zu finden ist er hier ExamFileServiceTest.shouldReturnMatchingExamNamesAndAmount:94. Ausserdem wären vielleicht noch mehr Tests angebracht.
- [ ] Eventuell noch ein kurzes cleanup das alles gut ist.

**Comment by Miguel7373** [comment]
## Stand 29.08.2024

Das Meiste des tickets steht. Hier sind noch dinge die zu erledigen sind:

- [ ] Vielleicht noch mehr Tests angebracht.
- [ ] Eventuell noch ein kurzes cleanup das alles gut ist.

**Comment by RandomTannenbaum** [comment]
**Stand 30.08.2024**
Ich habe heute über das gesamte feature geschaut und behoben was mir aufgefallen. Ausserdem habe ich die Tests entsprechend angepasst. Was allerdings noch fehlt ist ein Test, der die exceptions testet, wenn keine Unterordner gefunden werden. Ich habe ohne powermock momentan keine Möglichkeit gefunden, eine Methode auf jeder Instanz einer Klasse zu mocken.

**Comment by ManuelMoeri** [comment]
### Stand 02.09.2024 nach dem Planning
- [ ] Versuchen eine Lösung ohne PowerMock für den fehlenden Test zu finden. Timeboxed: 1 Tag
- [ ] Falls keine Lösung gefunden wird, PowerMock verwenden

**Comment by pizzi-cato** [comment]
### Lösung ohne Powermock

a) Unschön ist aktuell, dass das Root Directory der Prüfungsablage hart codiert ist. 
b) Wenn das Root Directory parametrisiert wird, kann es gleichzeitig auch besser / einfacher getestet werden.
c)  Ein Beispiel zur Config und zum Test ist unter dem Branch `feature/12-test-with-config` zu finden.
