### ISSUE TITLE
Footer styling

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/unilu-pruefungsabfrage#123]
Als Kunde möchte ich ein einheitliches Layout der App haben, das das Entwicklungsteam mit dem Kunden abgesprochen hat.

### Anforderungen
- Der Footer ist anhand des folgenden Mockups gestyled.
![Image](https://github.com/user-attachments/assets/b51e8762-deb2-43c0-87c2-a8687946763a)

### Zusätzliche Informationen:
- Alle Links die klickbar sind sollen die folgende Farbe haben: #E5007D
- Die Farbe soll nicht jedes mal neu definiert werden sondern als variable im custom_bootstrap definiert werden

### Akzeptanzkriterien
- [x] Die aufgeführten Anforderungen sind alle erfüllt.
- [x] Die Tests sind entsprechend angepasst.

**Comment by RandomTannenbaum** [comment]
**Stand 30.09.2024**
Ich habe den Footer grundsätzlich angepasst, damit er dem Styling aus dem Mockup entspricht.

Was noch fehlt:
- Wir sind uns noch nicht ganz sicher wie wir den footer positionieren wollen. Sticky immer am unteren Bildschirmrand oder immer ganz unten?
- Die Links müssen nach neuen Anforderungen immer rosa gefärbt sein
