### ISSUE TITLE
AAI: Testing

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#139]
Als Entwickler möchte ich die vorhandenen Tests (JUnit, IT, E2E) wie bisher ausführen können, sowohl lokal als auch dem Build Server. Dazu muss die Authentisierung für die Tests angepasst werden.

Dies ist eine Folge-Story zu [Switch AAI als Login anbinden](https://github.com/puzzle/unilu-pruefungsabfrage/issues/1).

### Anforderungen
- Die Tests (JUnit, IT, E2E) müssen weiterhin ausgeführt werden können.
- Das HTTP-Protokoll spielt für die Tests keine wesentliche Rolle; je nach Ansatz sind HTTP oder HTTPS möglich.
- Es kann davon ausgegangen werden, dass entweder keine Authentisierung notwendig ist oder die Pre-Authentication bereits durchgeführt worden ist (und in den Tests simuliert wird).
- Das Verhalten der Authentisierung bzw. der vorliegenden Benutzerdaten kann (je nach Testfall) angepasst werden. Z.B. kann die Matrikelnummer leer sein, um das Verhalten Applikation bei fehlender Matrikelnummer zu prüfen.

### Akzeptanzkriterien
- [ ] obige Anforderungen sind alle erfüllt
- [ ] die Tests (JUnit, IT, E2E) sind nachgeführt und können sowohl lokal als auch auf dem Build Server ausgeführt werden.

**Comment by MasterEvarior** [comment]
Wurde bereits im #1 umgesetzt, kann also geschlossen werden.
