### ISSUE TITLE
AAI: Festlegung gesicherte / ungesicherte Bereiche

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#140]
Als Entwickler möchte ich klare Bereiche festlegen, welche gesichert bzw. ungesichert aufgerufen werden können. In den gesicherten Bereichen ist die Authentisierung zwingend notwendig und die Benutzerinformationen sind im Request vorhanden. Im ungesicherten Bereich ist die Authentisierung nicht notwendig und die Benutzerinformationen sind nicht im Request vorhanden.

Dies ist eine Folge-Story zu [Switch AAI als Login anbinden](https://github.com/puzzle/unilu-pruefungsabfrage/issues/1).

### Anforderungen

- Die Bereiche gesichert / ungesichert sind klar festgelegt.
- Der Reverse Proxy ist korrekt konfiguriert für gesicherte und ungesicherte Bereiche.
- Der ShibbolethRequestAuthenticationFilter ist korrekt implementiert für gesicherte und ungesicherte Bereiche.
- Die SecurityConfig ist korrekt implementiert für gesicherte und ungesicherte Bereiche.

### Akzeptanzkriterien
- [ ] obige Anforderungen sind alle erfüllt
- [ ] die Konfiguration für Test- und Prod-Umgebung sind nachgeführt
- [ ] die Bereiche sind sauber getestet und dokumentiert

**Comment by MasterEvarior** [comment]
Durch das entfernen der /home-Seite, haben sich die unterschiedlichen Bereichen erledigt. Neu ist alles gesichtert.
