### ISSUE TITLE
AAI: Offizielles Zertifikat und Public Key einbinden

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#142]
Als Betreiber der EFT Applikation möchte ich offizielle (keine self-signed) Zertifikate und Public Keys verwenden.

Dies ist eine Folge-Story zu [Switch AAI als Login anbinden](https://github.com/puzzle/unilu-pruefungsabfrage/issues/1).

### Anforderungen

- Das offizielle Zertifikat ist bestellt und in der Applikation eingebungen.
- Der dazugehörige Public Key ist in der Applikation eingebunden.

### Akzeptanzkriterien

- [ ] obige Anforderungen sind alle erfüllt
- [ ] die Dokumentation der EFT Applikation ist nachgeführt

**Comment by MasterEvarior** [comment]
Kann geschlossen werden, da die Zertifikate beim Deployment per Volume in das Image gemounted werden. Das wird im #141 erledigt.
