### ISSUE TITLE
AAI: EFT Delivery

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#143]
Als Betreiber der EFT Applikation möchte ich ein möglichst einfache Form des Applikation - im Idealfall ein Docker(-Compose) Image, welches ausgeführt werden kann. Die interne Zusammenstellung der notwendigen Komponenten (Apache Web Server, Shibboleth Service Provider, Reverse Proxy und Spring Boot Applikation (inkl. Tomcat und EFT App)) ist für mich als Betreiber sauber verpackt und von aussen konfigurierbar.

Dies ist eine Folge-Story zu [Switch AAI als Login anbinden](https://github.com/puzzle/unilu-pruefungsabfrage/issues/1).

### Anforderungen

- Die interne Zusammenstellung der Komponenten ist festgelegt.
- Die zusammengehörigen Komponenten werden in Docker Images zusammengefasst.
- Die notwendigen Konfiguration der Komponenten ist von "aussen" möglich.

### Akzeptanzkriterien

- [ ] obige Anforderungen sind alle erfüllt
- [ ] die Dokumentation der EFT Applikation ist nachgeführt

**Comment by MasterEvarior** [comment]
**Stand 18.10.24**
Alle nicht-sensitive Files in das GitHub-Repo migriert und angefangen das Docker-Image so umzuschreiben das die Secrets nicht mehr im Image selber sind.

TODOs:
- [ ] Image fertig refactoren
- [ ] README.md anpassen
- [ ] Testen

**Comment by RandomTannenbaum** [comment]
**Stand 25.10.2024**
Heute haben wir die PR weiter überarbeitet. Die conversations aus dem review von Paco habe ich auch resolved. Die PR ist bereit für ein weiteres review.
