### ISSUE TITLE
Download Methode für einzelnes File

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#15]
Als Student möchte ich die Möglichkeit haben, einzelne Prüfungen herunter zu laden. Dafür sollen die Prüfungen als Link im Template angezeigt werden. 

### Anforderungen
- Beim Klicken auf einen Link, wird der Download der entsprechenden Prüfung ausgelöst.
- Der Download der Prüfung geschieht automatisch nach Klicken des Links und der User bleibt auf der selben Ansicht.

### Akzeptanzkriterien
- [x] Die heruntergeladene Datei hat den Namen des Ordners in welchem die Prüfung abgelegt ist.
- [x] Das Feature ist sauber getestet (Smoke-, Unit-, E2E-Tests)
- [x] Der Input (Prüfungslaufnummer, Ordnernamen) sind validiert. 
- [x] Falls ein ungültiger Request abgesetzt wird, wird dem User eine Fehlermeldung angezeigt.

**Comment by Miguel7373** [comment]
Die Ansicht bleibt identisch aber wenn in deinen browser einstellungen deklariert ist das sich pdf's beim download öffnen wird es in einen neuen tab geöffnet
