### ISSUE TITLE
MIME type missmatch

### ISSUE THREAD

**Issue by Miguel7373** [puzzle/unilu-pruefungsabfrage#150]
Aktuell wird im Main ein MIME-Type Error angezeigt, da wir keine Fehlermeldungen in der Console des Webbrowsers sehen wollen, muss dieser entfernt werden.

### Anforderungen

- Die ungwollte Fehlermeldungen wurde aus der Konsole enfernt
- Im falle das die Fehlermeldung nicht entfernt werden kann wurde dies beim Ursprung so dokumentiert

### Akzeptanzkriterien

- [x] Alle Anforderungen wurden erfüllt
- [ ] Das Feature wurde smoke getestet

**Comment by MasterEvarior** [comment]
The issues was that a stylesheet `styles/footer.css` was referenced, which does not exist. This leads Spring Boot to redirect to `/error`, which does serve `text/html` and not `text/css` as expected. Hence the MIME-type missmatch
