### ISSUE TITLE
Zip Download

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#16]
Als Student möchte ich die Möglichkeit haben, alle meine Prüfungen einer Prüfungslaufnummer zusammen herunter zu Laden. Diese Funktionalität stellen wir in als .zip download zur Verfügung.

Basis für diese Story ist die erfolgreiche Suche (Student + Prüfungslaufnummer), d.h. mehrere Prüfungen zum Download vorliegen.

### Anforderungen
- Alle Prüfungen einer Prüfungslaufnummer des jeweiligen Studenten können als .zip file heruntergeladen werden
- Die Prüfungen haben den Namen ihres entsprechenden Folders
- Die .zip Datei hat einen Namen, welcher die Prüfungslaufnummer enthaltet.

### Akzeptanzkriterien
- [ ] Die oben erwähnten Anforderungen sind erfüllt. 
- [ ] Das Naming der .zip Datei ist einfach Leserlich und enthält die Prüfungslaufnummer
- [ ] Das Feature ist sauber getestet (Smoke-, Unit-, E2E-Tests)

**Comment by ManuelMoeri** [comment]
### Stand 29.08.2024
Bis jetzt wurde nur Code aus dem Beispiel projekt kopiert und ein bisschen exception handling betrieben. Noch nichts grosses.

Bsp-Projekt: https://gitlab.puzzle.ch/pitc_lehrausbildung/beispiele/fileshare_uebung/-/tree/thymeleaf-test?ref_type=heads

**Comment by ManuelMoeri** [comment]
### Stand 06.09.2024
Die Logik & das Testing ist beendet. Das einzige das noch fehlt ist das dazugehörige Frontend. Dies kann aber erst implementiert werden nachdem das Ticket #17 beendet wurde, da der Button zum Herunterladen des ZIP's erst nach dem Suchen auftauchen sollte.

Im moment failed noch der letzte Test im 'ExamFileServiceTest' file. Der Test funktioniert  Lokal problemlos, aber sobald er mit `mvn test -Dtest=ExamFileServiceTest` oder auf der Pipeline ausgeführt wird, failed er. Die Ursache ist klar ersichtlich jedoch nicht wie man diese beheben kann.

**Comment by ManuelMoeri** [comment]
### Stand 09.09.2024
Das Frontend des Tickets wurde implementiert. Alles funktioniert bis auf den Test wie schon im letzen Kommentar erwähnt. Der Test heisst `shouldReturncorrectFilesAfterZip` und ist im `ExamFileServiceTest` zu finden. Dort ist immer noch das problem das es Lokal funktioniert jedoch sobald man es auf der Pipeline oder mit dem mvn command runnt, nicht mehr.

**Comment by Miguel7373** [comment]
### Stand 10.9.2024

Die Tests sollten laufen. Es muss aber noch geschaut werden, wie man die ö ü usw. handled da die Filenamen in dem ZIP corrupted werden, wenn sie ein Sonderzeichen enthalten. Das Charset kann beim ZipOutputStream hinzugefügt (bei uns hat das jedoch noch nichts gebracht).

**Comment by ManuelMoeri** [comment]
> ### Stand 10.9.2024
> 
> Die Tests sollten laufen. Es muss aber noch geschaut werden, wie man die ö ü usw. handled da die Filenamen in dem ZIP corrupted werden, wenn sie ein Sonderzeichen enthalten. Das Charset kann beim ZipOutputStream hinzugefügt werden (bei uns hat das jedoch noch nichts gebracht).

### Fix für den encoding Fehler
1. Es ist festzuhalten das der encoding Fehler nur passiert wenn die gedownloadeten files nicht entzippt werden. Falls das Zip einfach extracted wird ist das naming tadellos.

2. Ich habe das fehlerhafte naming bei einem nicht extracteden Zip file in einem HEX editor angeschaut und der Buchstabe wird von  UTF-8 als Ü erkennt. Dies stimmt auch. Der eigentliche Fehler liegt beim default archive manager von Ubuntu. Wie [hier](https://askubuntu.com/questions/443273/cannot-read-filenames-that-are-in-utf8-encoding-greek-characters) beschrieben ist der schlicht und einfach nicht in der Lage non-englische files korrekt zu lesen.
