### ISSUE TITLE
Docker compose setup mit Rootless docker

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/unilu-pruefungsabfrage#167]
Momentan scheint es noch ein paar bugs zu geben wenn man das docker compose setup mit rootless docker ausführt.

Was aufgefallen ist:
- Die Applikation scheint zwar im rootless Modus zu starten, ist aber dann über `edview.unilu.ch` nicht erreichbar.

Was schon gelöst wurde:
Der Keystore wird standardmässig mit read-write permission für den Ersteller erstellt, jedoch nicht für andere. Im Readme des Tickets #141 haben wir dies bereits beschrieben.

### Anforderungen
- [x] Dev und prod docker compose können beide mit rootless Docker ausgeführt werden und die Applikation ist voll funktionsfähig.

**Comment by kapicomk** [comment]
docker

**Comment by MasterEvarior** [comment]
### Stand 07.11.2024
Die Docker-Compose-Files sollten nun mit rootless Docker funktionieren. Es muss die korrekte Adresse für den AJP-Endpoint gesetzt werden, was in diesem Fall der Localhost ist. Damit ist es dann auch konsistent mit der Adresse für HTTP.

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 172.25.0.3:8443         0.0.0.0:*               LISTEN      50135/java
tcp        0      0 172.25.0.3:8448         0.0.0.0:*               LISTEN      50135/java
tcp        0      0 0.0.0.0:35729           0.0.0.0:*               LISTEN      50135/java
tcp        0      0 127.0.0.11:39325        0.0.0.0:*               LISTEN      3088/dockerd
tcp6       0      0 :::5005                 :::*                    LISTEN      50135/java
udp        0      0 127.0.0.11:39722        0.0.0.0:*                           3088/dockerd
```
Sobald @RandomTannenbaum verifiziert hat, das es auch bei ihm läuft,  kann man mergen.
