### ISSUE TITLE
Input von Prüfungslaufnummer

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#17]
Als Student muss ich die möglichkeit haben die Prüfungslaufnummer der aktuellen Prüffungs Session einzugeben. Damit ich die Prüfungen vom aktuellen Semester bekomme.

### Anforderungen
- Ein Input Feld existiert, wo die Prüfungslaufnummer eingegeben werden kann
- Das Inputfeld hat Placeholder wo ein Beispiel für eine Prüfungsnummer hinterlegt ist 
- Das Inputfeld ist ein Pflichtfeld und mit einem Asteriks als solches markiert
- Der Absendebutton ist disabled falls keine Prüfungslaufnummer eingegeben worden ist
- Im Backend wird die Prüfungslaufnummer validiert mithilfe eines Validation Service. 

### Akzeptanzkriterien
- [ ] Die oben beschriebenen Anforderungen sind alle erfüllt
- [x] Der Validator überprüft anhand eines regex, dass nur 5 stellige Nummern erlaubt sind
- [x] Falls eine invalide Prüfungslaufnummer eingegeben worden ist soll eine entsprechende Fehlermeldung angezeigt werden
- [x] Das Feature ist getestet (Smoke-, Unit-, E2E-Tests)

**Comment by RandomTannenbaum** [comment]
**Hinweis für Validation im Frontend:**
Auf einem HTML input field kann das `pattern` Attribut gesetzt werden, welchem ein Regex übergeben werden kann. Nur Inputs die diesem Regex entsprechen, können auch abgesendet werden. Wenn man zusätzlich noch die error message des Input fields erweitern will, kann das `title` Attribut gesetzt werden.

https://www.w3schools.com/tags/att_input_pattern.asp

**Comment by nevio18324** [comment]
Alle Anforderungen erfüllt bis auf das der Button disabled ist bei keinem Input. Ich habe mit Thymeleaf keine Option gefunden dies umzusetzen und sehe es auch nicht als nötig da die Form nicht absendbar ist ohne das Input feld ausgefüllt zu haben.

**Comment by pizzi-cato** [comment]
Aktuell validieren wir an drei Stellen: client-seitig anhand des Patterns, server-seitig mit der Methode viewValidatePage(@Valid ...) und schliesslich auch im Validation Service. Gemäss Beispiel https://spring.io/guides/gs/validating-form-input würde ich im Moment auf die client-seitige Validierung verzichten, solange wir nicht Scripts im client verwenden (Validierung, enable / disable Submit Button).

**Comment by pizzi-cato** [comment]
Der PR kann nicht gemergt werden, da er im Konflikt mit dem main Branch steht.
