### ISSUE TITLE
Renaming der Files

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#18]
Als User möchte ich sofort erkennen, welche Prüfung ich heruntergeladen habe. Dafür werden die Prüfungen umbenannt. 

### Anforderungen
- Die Prüfungen sind in einem Ordner, welcher den Namen des Moduls hat, als pdf abgelegt
- Der Name der Prüfung auf dem Filesystem entspricht dem Format: `24000_19103106.pdf` 
- Der Anzeigenamen der Prüfung, sowohl beim Download wie auch beim Anzeigen der Links ist der Ordner Name in welchem die Prüfung liegt.

### Akzeptanzkriterien
- [x] Nach dem auslesen aus dem FS wir die Prüfung immer mit dem Ordnernamen benannt. 
- [ ] Alle oben aufgeführten Anforderungen sind erfüllt.
- [ ] Das Feature ist sauber getestet (Smoke-, Unit-, E2E-Tests)

**Comment by Miguel7373** [comment]
Um den nahmen des Download files zu ändern kann man mit setHeader des responses dies ändern. Der Anzeigename ist bereits in dem Filemodel im getter geändert.
