### ISSUE TITLE
Sonar Cube

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#20]
Als Entwickler möchte ich sicher stellen, dass der Code sauber und möglichst ohne Bugs ist. Dafür verwenden wir ein Tool zur statischen Codeanalyse.

### Anforderungen
- Wir verwenden Sonar Cube von Puzzle und erstellen ein Projekt wo wir die Codequalität tracken
- Wir wollen die Tests bei der Code Qualität ausklammern
- Die aktuelle Codequality soll in einer Pipeline auf SonarCube gepushed werden.

### Akzeptanzkriterien
- [x] Es existiert ein Sonar Cube Projekt
- [x] Bei jedem Merge auf den Main Branch wird die Code Qualität in Sonar Cube aktualisiert.

**Comment by ManuelMoeri** [comment]
**Stand 15.08.2024**
Der Fortschritt sieht wie folgt aus: Es ist möglich den command lokal auszuführen, jedoch funktioniert es auf der Pipeline noch nicht. Paco ist da daran dies zu fixen. Der command lokal sieht wie folgt aus:
`mvn sonar:sonar -Dsonar.host.url=https://sonar.puzzle.ch -Dsonar.projectKey=unilu-exam-feedback-tool -Dsonar.login=<Your_LOGIN_Token>` zu finden sind die resultate dann [hier](https://sonar.puzzle.ch/dashboard?id=unilu-exam-feedback-tool). 'Your_LOGIN_Token' kann ebenfalls auf sonar.puzzle.ch erstellt werden. Dabei kann jeder sein eigenes verwenden.

ToDo:
- [ ] Das 'sonar-project.properties" file sollte vervollständigt werden. Ziel ist es Dsonar.host.url & Dsonar.projetKey vom command zu entfernen und diese in diesem file zu dokumentieren. Dieses file muss auch noch irgendiwie "aktivert" werden.
- [ ] Ausserdem sollen noch die Tests bei der code quality ausgeklammert werden. Sollte ebenfalls in diesem file möglich sein.

**Comment by Miguel7373** [comment]
Lockal funktioniert es mit disem command:  
`mvn clean verify sonar:sonar -Dsonar.login=<Your_LOGIN_Token>`
'Your_LOGIN_Token' kann ebenfalls auf sonar.puzzle.ch erstellt werden. Dabei kann jeder seinen eigenen verwenden.

**Comment by ManuelMoeri** [comment]
### Stand 22.08.2024
Das Ticket ist beendet. Da es jedoch den gleichen branch wie das #37 Ticket hat, ist es solange in progress bis das andere fertig ist.
