### ISSUE TITLE
Validation Service

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#22]
Als Entwickler will ich sicherstellen, dass nur validierte Befehle ausgefürht werden. Somit stellen wir auch sicher, dass wir dem angemeldeten Studenten nur seine eigene Prüfung anzeigen. 

### Anforderungen
- Ein Validation Service ist geschrieben, welcher die Validation der Prüfungslaufnummer übernimmt
- Die Matrikel Nr wird aktuell **nicht** validiert und ggf. später in einer neuen Story aufgenommen
- Dieser Validation Service kann von anderen Services verwendet werden um sicherzustellen, dass der Input dem entsprechend erwarteten Input entspricht.

### Akzeptanzkriterien
- [x] Der Validation Service kann erweitert werden
- [x] Die Oben genannten Anforderungen sind erfüllt
- [x] Testing (Smoke-, Unit-Tests)

**Comment by RandomTannenbaum** [comment]
**Stand 19.08.2024**
Das Ticket ist eigentlich fertig. Ich schaue morgen nochmal drüber ob alles vorhanden ist und ob evtl. noch gerebased werden muss.

**Comment by pizzi-cato** [comment]
**Anpassung der Anforderungen**

Die Matrikel Nr wird aktuell nicht validiert und ggf. später in einer neuen Story aufgenommen
