### ISSUE TITLE
Testing Frameworks aufsetzen

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#3]
Als Entwickler möchte ich sicherstellen, dass mein Code den Anforderungen entspricht. Für das weitere Entwickeln gibt mir dies eine gewisse Sicherheit, dass weniger Bugs entstehen.

### Anforderungen
- Die Frameworks für Unit Tests sind aufgesetzt
- Es werden Controller und Services getestet
- Einfache Beispiel Tests sind geschrieben
- Es existiert eine Überprüfung auf die Codecoverage, wir streben 80%  Testabdekung auf Line und Branch an.
- Es werden E2E Tests mit Cypress ausgeführt, dazu werden Testing Containers verwendet.

### Akzeptanzkriterien
- [x] Die oben aufgeführeten Anforderungen sind Vollumfänglich und konsistent über das ganze Projekt implementiert

**Comment by RandomTannenbaum** [comment]
**ToDo**
- Check if readonly is enough for ressource mapping on test container
- Clean up JaCoCo config
- E2E Test Coverage

**Comment by RandomTannenbaum** [comment]
**Stand Cypress mit Code Coverage**
Cypress stellt zwar ein [coverage plugin](https://github.com/cypress-io/code-coverage) zur Verfügung, dieses alleine erstellt allerdings noch keine coverage reports. Dafür braucht man [Istanbul.js](https://istanbul.js.org/), welches den Code instrumented. Dieses instrumented aber nur JS-Files. Dadurch wird nur überprüft, wie viel Prozent des Javascript Codes beim Durchklicken des UIs ausgeführt wird, nicht jedoch, was auf der Seite effektiv alles bedient wird.

Cypress scheint kürzlich die sogenannte [UI Coverage](https://www.cypress.io/blog/introducing-ui-coverage) vorgestellt zu haben, diese steht allerdings noch im early access.

**Comment by RandomTannenbaum** [comment]
**Stand 14.08.2024**
Ich habe in der JaCoCo config die unnötigen Steps mit den Integration tests entfernt. Die Coverage wird jetzt direkt aus den Unit Tests erstellt. Ausserdem habe ich die example unit tests noch ein bisschen aufgeräumt und den zwei controller endpoints je ein eigenes Viewfile gegeben.
