### ISSUE TITLE
Renovate Bot

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#4]
Als Entwickler und User möchte ich Software, die immer auf dem aktuellsten Stand ist. Damit wir dies nicht manuell tracken müssen, wollen wir den Renovate Bot im Repository hinzufügen.

### Anforderungen
- Renovate ist im Repository hinzugefügt und kann automatisch Pullrequests mit updates eröffnen.

### Akzeptanzkriterien
- [ ] Die oben aufgeführeten Anforderungen sind Vollumfänglich und konsistent über das ganze Projekt implementiert

**Comment by RandomTannenbaum** [comment]
Hilfreiche Links:
https://docs.puzzle.ch/user-guides/renovate-user-guide/index.html
https://github.com/puzzle/okr/pull/405
