### ISSUE TITLE
Schriftart wird lokal bereitgestellt

### ISSUE THREAD

**Issue by kcinay055679** [puzzle/unilu-pruefungsabfrage#68]
Als Student möchte ich die Möglichkeit haben, dass der Text einfach leserlich und in Einheit mit den restlichen Applikationen der Uni Luzern ist.

### Hinweise
Laut Styling Guide wäre die Schriftart 'Minion: Französische Renaissance-Antiqua' auf der Webseite zu verwenden. Jedoch ist diese Kostenpflichtig und die Uni Luzern besitzt Lizenzrechte nur für ihre eigene Webseite. Nach weiterer absprache mit dem Kunden hat er sich für Arial entschieden, da dies recht ähnlich aussieht.

### Anforderungen
Die Schrift Arial wird lokal bereitgestellt

### Akzeptanzkriterien
- [ ] Die Schriftart ist lokal bereitgestellt
- [ ] Alle Anforderungen sind erfüllt

**Comment by Miguel7373** [comment]
Die Schriftart Arial ist eine Microsoft Font und braucht deswegen eine Lizenz. Nach ein wenig Suche würde ich also eine Google Font, die fast genau gleich aussieht, in Betracht ziehen. Open Sans sieht nicht nur fast identisch zu Arial aus, sondern ist auch noch von Google also nach mir Komplet free to use.

**Comment by Miguel7373** [comment]
### Stand 17.9.24

Ich habe erstmal die Schrift OpenSans-Regular lokal bereitgestellt und habe es in das Styles.css implementiert.

To-do

- [ ] Überprüfe, ob das @font-face nicht in ein eigenes CSS muss.
- [ ] Stelle noch woff und woff2 lokal zur Verfügung.
- [ ] Spreche ab, ob die Schrift für das Okay ist (Paco oder Christoph) sonst nach anderen Möglichkeiten suchen.
