### ISSUE TITLE
Alternative Testabdeckungen zu jacoco evaluieren

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#69]
Als Entwickler möchte ich die Testabdeckung sowohl im maven build als auch mit SonarQube durchführen können. Das eingestzte maven Plugin **jacoco-maven-plugin** basiert jedoch auf dem Ansatz "bytecode instructions", SonarQube hingegen verwendet "executable lines". Das Resultat dieser beiden Tools bzw. Ansätze ist sehr unterschiedlich und für die Qualitätskontrolle erkärungsbedürftig.

siehe auch TechTalk [JaCoCo vs SonarQube code coverage](https://codimd.puzzle.ch/gVHit3wiRf-HluAk4EmTxA)

### Anforderungen
 
- Es werden mehrere Alternativen zur Testabdeckung evaluiert und dokumentiert.
- Die Alternativen müssen als maven Plugin ausgeführt und ausgewertet werden können (Code Coverage).
- Die Code Coverage muss als Qualtitätskontrolle im Build Process überprüft werden können.
- Die Alternativen werden im Team vorgestellt und eine Alternative wird ausgewählt / bestimmt.

### Akzeptanzkriterien

- [ ] Die oben gelisteten Anforderungen sind vollumfänglich erfüllt.
- [ ] Die Alternativen sind dem Team vorgestellt worden.
- [ ] Eine Alternative wurde bestimmt und kann in der Folge-Story umgesetzt werden.

**Comment by ManuelMoeri** [comment]
# Stand 12.09.2024
Sämtliche Resultate wurden in diesem Codi festgehalten: https://codimd.puzzle.ch/q8BNB5e7S2S5EcmZNVT76g?both#
Bis jetzt habe ich erst eine wirklich gute Alternative gefunden. Diese heisst OpenClover und deckt alle unsere Anforderungen ab.

### Hinweis
Vielleicht ist noch anzumerken das wir kein Tool mit Bytecode Instructions verwenden sollten, weil wir sonst wieder ein ähnliches Behaviour wie mit JaCoCo haben.

**Comment by RandomTannenbaum** [comment]
**Stand 17.09.2024**
Ich habe heute noch weiter nachgeforscht. Dabei habe ich unter anderem auch, wie es @ManuelMoeri schon beschrieben, OpenClover gefunden. Ich bin mir jedoch recht sicher dass dies das "Problem" lösen würde. Meiner recherche nach ist die Diskrepanz in den Ergebnissen von JaCoCo und SonarQube nicht wirklich ein Problem.

Dafür spricht auch, dass die offizielle Sonar-Dokumentation auch JaCoCo für Java test coverage beschreibt und benutzt:
https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/test-coverage/java-test-coverage/

Ausserdem hat SonarQube hier beschrieben was sie als executable erachten und was nicht. Da dies jedoch ihre eigene Methode des Zählens von Lines ist und sie selber kein plugin für coverage zur Verfügung stellen, wird man wohl kein Plugin finden dass die Selbe Coverage wie SonarQube berechnet.
https://docs.sonarsource.com/sonarqube/latest/extension-guide/developing-a-plugin/executable-lines/

Dies haben sie auch in diesem Blog-Eintrag beschrieben, als sie executable lines gerade neu eingeführt hatten:
https://www.sonarsource.com/blog/executable_lines/
