### ISSUE TITLE
Alternative Testabdeckung umsetzen

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#70]
Als Entwickler möchte ich die Testabdeckung sowohl im maven build als auch mit SonarQube durchführen können. Das eingestzte maven Plugin **jacoco-maven-plugin** basiert jedoch auf dem Ansatz "bytecode instructions", SonarQube hingegen verwendet "executable lines". Das Resultat dieser beiden Tools bzw. Ansätze ist sehr unterschiedlich und für die Qualitätskontrolle erkärungsbedürftig.

siehe auch TechTalk [JaCoCo vs SonarQube code coverage](https://codimd.puzzle.ch/gVHit3wiRf-HluAk4EmTxA)

### Vorbedingungen
 
- In der Vorgänger-Story [Alternative Testabdeckungen evaluieren](https://github.com/puzzle/unilu-pruefungsabfrage/issues/69) wurde die Alternative ausgewählt.

### Anforderungen
 
- Der Build Prozess wird auf die ausgewählte Alternative umgestellt.
- Sowohl der lokale Build als auch die Build Pipelines verwenden die ausgewählte Alternative.
- Das Qulitätsmerkmal der Code Coverage ist im Build Process korrekt hinterlegt / angepasst.

### Akzeptanzkriterien

- [ ] Die oben gelisteten Anforderungen sind vollumfänglich erfüllt.

**Comment by peggimann** [comment]
We did not find a suitable alternative to jacoco
