### ISSUE TITLE
Naming des ExamDownloadControllers

### ISSUE THREAD

**Issue by ManuelMoeri** [puzzle/unilu-pruefungsabfrage#72]
### Naming
Im moment heisst der Controller zum Downloaden der Files 'ExamDownloadController'. Jedoch heisst der service und das Model dazu 'ExamFileService' & 'ExamFile'. Dies stimmt nicht mit dem Controller überein. In der Definiton unserer REST-schnittstelle steht nocheinmal etwas anderes.

In https://codimd.puzzle.ch/6BJmVlkUQLKGo77MLkFNnQ# steht das alles unter der /exams route gedownloadet werden sollte. Dieses Codi ist eigentlich auch die Source of Truth. --> Kurz mit Paco oder Christoph absprechen wie das Model, der Service & der Controller wirklich heissen sollen.

### Anforderungen
- Das Naming wurde mit Christoph oder Paco besprochen
- Das Naming wurde konsistent implementiert
- Tests wurden wenn nötig angepasst

**Comment by nevio18324** [comment]
### Stand 16.9 ###
Alle endpoints und der Klassenname vom ExamDownloadController wurde geändert wie im [Doc](https://codimd.puzzle.ch/6BJmVlkUQLKGo77MLkFNnQ#) vorgeschlagen ausser den endpoint der downloadfile Methode dieser nicht da der derzeitige endpoint mehr Sinn ergibt als der im Doc
