### ISSUE TITLE
Error Page für System Fehler

### ISSUE THREAD

**Issue by pizzi-cato** [puzzle/unilu-pruefungsabfrage#76]
Als Anwender kann ich mit der allgemeinen Error Page nichts anfangen.

![Image](https://github.com/user-attachments/assets/9d92ce28-409d-44c0-b8b8-4883a52169b4)

Es genügt, wenn ich sehe, dass etwas schief gelaufen ist und das die Applikation im Moment nicht korrekt funktioniert.

### Anforderungen
- Eine Error Page / Error Handler soll die allgemeinen, nicht speziell abgefangenen Fehler in einer "benutzerfreundlichen" Form anzeigen.
- Der Fehler wird korrekt geloggt.
- Es soll mit dem Kunden abgeklärt werden, was alles auf der Error Page ausgegeben werden soll / darf, siehe [Vorschlag](https://codimd.puzzle.ch/2mbobSvPSMC_OVHx-Umdyw).
- Die gewünschte Lösung wird korrekt umgesetzt.

### Akzeptanzkriterien
- [x] Allgemeine Fehler werden in einer Error Page dem Anwender in einer "benutzerfreundlichen" Form angezeigt.
- [x] Die oben beschriebenen Anforderungen sind alle erfüllt.

**Comment by nevio18324** [comment]
### Stand 17.9 ###
Die Funktionalität ist da jedoch mit 2 Problemen

1. Bei einem localhost:8080// mapping fängt dies der Errorhandler zwar ab aber alle imports die durch einen Relativen Pfad importiert sind funktionieren nicht, dass passiert nur bei einem // mapping bei einem /xxx/ funktioniert es einwandfrei.
2. Stand jetzt wird mit redirect:error auf die error page weitergeleitet was dazu führt das man keine Attribute dem Model hinzufügen kann

Für Problem 1 habe wir noch keine Ursache oder Lösung gefunden.
Problem 2 wäre lösbar mit einer pathvariable.

**Comment by nevio18324** [comment]
### Stand 17.9 ###
Ich konnte das 1. Problem noch lösen es lag daran wenn man ein localhost:8080// mapping sucht wirft Springboot kein Fehler aber bei einem localhost:8080/xxx/ macht es dies, weswegen das eine vom ExceptionController abgefangen wird und das andere nicht, jedoch kam das error.html trozdem da Springboot in dieser Situation standartmässig auf /error forwarded ich konnte dies nun lösen in dem ich im application.properties den Error path auf redirect:/error geändert habe.
