### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by peggimann** [puzzle/unilu-pruefungsabfrage#9]
Als Kunde möchte ich eine einfache Methode haben um die Applikation zu betreiben. Dazu wollen wir dem Kunden ein Docker Image zur verfügung stellen, wo ein FS gemounted werden kann. 

### Anforderungen
 ~~Ein Build erstellt ein Docker Image~~ 
- Bei diesem Docker Image kann ein FS gemounted werden in einen definierten folder.

### Akzeptanzkriterien
~~Beim ausführen des mvn build command wird ein docker image gebaut, mit den angegebenen properties.~~

Das Spring-Boot build image goal [scheint das Dockerfile komplett zu ingnorieren](https://medium.com/@ramanamuttana/build-a-docker-image-using-maven-and-spring-boot-418e24c00776). Es wird nur ein Container gebuildet, auf dem automatisch das gebuildete JAR läuft. Deswegen benutzen wir später auf der Pipeline ([siehe dieses Ticket](https://github.com/orgs/puzzle/projects/13/views/1?pane=issue&itemId=73987900)) die Methode, die wir auch schon im OKR verwendet haben.

Das Image kann Lokal natürlich ganz normal mit dem Build command gebuildet werden.

**Comment by RandomTannenbaum** [comment]
**Stand 14.08.2024**
Ich habe das Ticket etwas aufgeräumt und ein Problem im Dockerfile gefixt. Es sollte jetzt read for review sein.
