### ISSUE TITLE
Mockups erstellen

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/unilu-pruefungsabfrage#96]
Da wir keine genaue Vorgabe erhalten haben, wie die Applikation aussehen soll, wollen wir Mockups des UIs der Applikation erstellen. So kann der Kunde sich dann genauer vorstellen wie die finale Applikation aussehen wird und schon frühzeitig Änderungen einbringen. Ausserdem habe wir so etwas, an dem wir uns beim Entwicklung orientieren können.

### Mockup files
Die Mockup files können hier abgelegt werden:
https://files.puzzle.ch/apps/files/files/7161750?dir=/jpulfer%20diverses/Unilu-Pruefungsabfrage-Mockups

**Comment by nevio18324** [comment]
### Stand 23.9 ###
Ich habe ihm nun die 4 Versionen gesendet und warte auf ein Feedback

**Comment by nevio18324** [comment]
### Stand 27.9 ###
Marco hat uns nun geantwortet und er und das Unikomm Team hätten am liebsten
dieses Mockup

![Image](https://github.com/user-attachments/assets/1404dd0a-35bc-4707-82bc-0cb273a54fa2)
